### ISSUE TITLE
Sugiro explicação sobre o que são Funções Anônimas/Lambda

### ISSUE THREAD

**Issue by thaissalzer** [heliomacedofilho/aspectos-de-programacao-para-ciencia-de-dados#11]
Sugiro alguma explicação, como a do livro:

As funções anônimas (também chamadas de lambda), são funções em Python que podem ser definidas sem a necessidade de um nome formal.
Essa é uma forma de escrever funções, constituídas de uma única instrução, cujo resultado é o valor de retorno. Elas são definidas com a palavra reservada lambda, que não tem outro significado a não ser dizer que "estamos declarando uma função anônima"

Local:
https://github.com/heliomacedofilho/aspectos-de-programacao-para-ciencia-de-dados/blob/main/02%20-%20Aspectos%20Nativos%20de%20Python%20%F0%9F%90%8D.ipynb?short_path=f5e857d#L3284

**Comment by heliomacedofilho** [comment]
sugestão acatada. introduzi a intuição por trás do conceito e coloquei uma explicação da origem da palavra reservada lambda.
