### ISSUE TITLE
Erro na execução do código (Código IBGE de Município)

### ISSUE THREAD

**Issue by thaissalzer** [heliomacedofilho/aspectos-de-programacao-para-ciencia-de-dados#15]
O código apresentou erro na hora de rodar as linhas abaixo:

Linhas:
execute_script('data', 'municipios_codigos.db', 'schema.sql', delete_script=True)
execute_script('data', 'municipios_codigos.db', 'data.sql', delete_script=True)
Local:
https://github.com/heliomacedofilho/aspectos-de-programacao-para-ciencia-de-dados/blob/main/03%20-%20Fontes%20de%20Dados%20%F0%9F%9A%B0%20%F0%9F%8E%B2.ipynb?short_path=bb522cd#L292

Erro:
---------------------------------------------------------------------------
UnicodeDecodeError                        Traceback (most recent call last)
~\AppData\Local\Temp\ipykernel_14788\2302335514.py in <module>
----> 1 execute_script('data', 'municipios_codigos.db', 'data.sql', delete_script=True)

~\AppData\Local\Temp\ipykernel_14788\854468283.py in execute_script(folder, database_filename, sql_filename, delete_script)
      7 
      8     with open(sqlpath) as sqlfile:
----> 9         script = sqlfile.read()
     10 
     11     cursor = cursor.executescript(script)

~\anaconda3\lib\encodings\cp1252.py in decode(self, input, final)
     21 class IncrementalDecoder(codecs.IncrementalDecoder):
     22     def decode(self, input, final=False):
---> 23         return codecs.charmap_decode(input,self.errors,decoding_table)[0]
     24 
     25 class StreamWriter(Codec,codecs.StreamWriter):

UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 12148: character maps to <undefined>

**Comment by heliomacedofilho** [comment]
Não consegui reproduzir o erro. Acredito que seja uma versão diferente do sqlite3.
Qual a versão do seu sqlite3? A minha é 2.6.0 (rodei o comando sqlite3.version para ver).
De qualquer forma, eu adicionei o parâmetro de codificação do arquivo (utf-8) conforme informado no arquivo sql (File generated with SQLiteStudio v3.2.1 on qui mar 11 13:15:09 2021 -- [Data.sql](https://github.com/andrebaltieri/ibge/blob/main/SQLite/Data.sql))

**Comment by thaissalzer** [comment]
A minha é 3.39.3 . Mas agora deu certo. Devia ser problema de versão diferente mesmo. Obrigada, Helio.
