### ISSUE TITLE
Sugiro ensinar a renomear variáveis do Dataframe

### ISSUE THREAD

**Issue by thaissalzer** [heliomacedofilho/aspectos-de-programacao-para-ciencia-de-dados#17]
Após ensinar a remover coluna do dataframe, sugiro ensinar a renomear:

Sugestão:
# Você pode renomear as colunas/variáveis do DataFrame 
frame1 = frame.rename(columns={"year": "ano", 'state': "Estado" })
frame1

Local sugerido: https://github.com/heliomacedofilho/aspectos-de-programacao-para-ciencia-de-dados/blob/main/06%20-%20Ana%CC%81lise%20de%20Dados%20%F0%9F%95%B5%F0%9F%8F%BD%20%F0%9F%8E%B2%20em%20Alto%20Desempenho%20%F0%9F%9A%80%20%F0%9F%A7%9E%E2%80%8D%E2%99%82%EF%B8%8F.ipynb?short_path=5c5b2a7#L2308

**Comment by heliomacedofilho** [comment]
adicionada orientação para renomear colunas e/ou índices
