### ISSUE TITLE
Erro na execução do código em concatenate_datasets('data', 'HIST_PAINEL_COVID')

### ISSUE THREAD

**Issue by thaissalzer** [heliomacedofilho/aspectos-de-programacao-para-ciencia-de-dados#18]
O código apresentou erro na hora de rodar as linhas abaixo:

Local que apareceu o erro:
https://github.com/heliomacedofilho/aspectos-de-programacao-para-ciencia-de-dados/blob/main/03%20-%20Fontes%20de%20Dados%20%F0%9F%9A%B0%20%F0%9F%8E%B2.ipynb?short_path=bb522cd#LL774C1-L774C1

Erro:
---------------------------------------------------------------------------
UnicodeDecodeError                        Traceback (most recent call last)
~\AppData\Local\Temp\ipykernel_16432\1844579710.py in <module>
----> 1 concatenate_datasets('data', 'HIST_PAINEL_COVID')

~\AppData\Local\Temp\ipykernel_16432\2872187963.py in concatenate_datasets(folder, filename_start)
     12                 csvreader = csv.reader(csvfile)
     13                 header = next(csvreader)
---> 14                 for row in csvreader:
     15                     rows.append(row)
     16             #os.remove(filepath)

~\anaconda3\lib\encodings\cp1252.py in decode(self, input, final)
     21 class IncrementalDecoder(codecs.IncrementalDecoder):
     22     def decode(self, input, final=False):
---> 23         return codecs.charmap_decode(input,self.errors,decoding_table)[0]
     24 
     25 class StreamWriter(Codec,codecs.StreamWriter):

UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 4207: character maps to <undefined>

**Comment by heliomacedofilho** [comment]
não consegui reproduzir o erro da codificação (deve haver alguma diferença de versão do python), mas adicionei a inserção do parâmetro de codificação (utf-8) para a abertura dos arquivos de casos e óbitos de covid-19

**Comment by thaissalzer** [comment]
O erro foi resolvido, Hélio. Obrigada. Destaco que na minha máquina demorou cerca de 5 minutos para rodar a concatenação. É bom ter isso em mente na hora da aula pois dependendo da máquina de quem estivem rodando poderemos ter algum problema em relação a isso.

**Comment by heliomacedofilho** [comment]
bem percebido. eu fiz um teste agora e reparei que a implementação, sem usar o DictReader/DictWriter, era bem mais rápida. Para mitigar um pouco esse tempo, vou fazer um rollback nessa implementação.

![Captura de Tela 2023-06-13 às 19 19 26](https://github.com/heliomacedofilho/aspectos-de-programacao-para-ciencia-de-dados/assets/2234749/432a0dc4-14de-4b13-9aea-bb08d4840f59)

**Comment by heliomacedofilho** [comment]
`import csv

def concatenate_datasets_DictReader(folder, filename_start = 'HIST_PAINEL_COVID'):
    folderpath, _ = build_path(folder)

    header, rows = None, []

    for file in os.listdir(folderpath):
        if file.startswith(filename_start) and file.endswith('.csv'):
            _, filepath = build_path(folder, 'raw', file)
            with open(filepath, encoding='utf-8') as csvfile:
                csvreader = csv.DictReader(csvfile, delimiter=';')
                header = csvreader.fieldnames
                for row in csvreader:
                    rows.append(row)
            #os.remove(filepath)

    _, filepath = build_path(folder, 'raw', 'ALL_' + filename_start + '.csv')
    with open(filepath, 'w', newline='') as csvfile:
        writer = csv.DictWriter(csvfile, fieldnames=header, delimiter=';')
        writer.writeheader()
        for row in rows:
            writer.writerow(row)


def concatenate_datasets_reader(folder, filename_start = 'HIST_PAINEL_COVID'):
    folderpath, _ = build_path(folder)

    header, rows = None, []

    for file in os.listdir(folderpath):
        if file.startswith(filename_start) and file.endswith('.csv'):
            _, filepath = build_path(folder, 'raw', file)
            with open(filepath, encoding='utf-8') as csvfile:
                csvreader = csv.reader(csvfile, delimiter=';')
                header = next(csvreader)
                for row in csvreader:
                    rows.append(row)
            #os.remove(filepath)

    _, filepath = build_path(folder, 'raw', 'ALL_' + filename_start + '.csv')
    with open(filepath, 'w', newline='') as csvfile:
        writer = csv.writer(csvfile)
        writer.writerow(header)
        for row in rows:
            writer.writerow(row)
`

`%%time
concatenate_datasets_DictReader('data', 'HIST_PAINEL_COVID')`


`%%time
concatenate_datasets_reader('data', 'HIST_PAINEL_COVID')`
