### ISSUE TITLE
erro de decodificação usando o codec UTF-8 na aula 6 

### ISSUE THREAD

**Issue by thaissalzer** [heliomacedofilho/aspectos-de-programacao-para-ciencia-de-dados#22]
na hora de rodar a linha 75: covid_infections_and_deaths = get_covid_infections_and_deaths(), aparece um erro de decodificação.

local: https://github.com/heliomacedofilho/aspectos-de-programacao-para-ciencia-de-dados/blob/main/06%20-%20Ana%CC%81lise%20de%20Dados%20%F0%9F%95%B5%F0%9F%8F%BD%20%F0%9F%8E%B2%20em%20Alto%20Desempenho%20%F0%9F%9A%80%20%F0%9F%A7%9E%E2%80%8D%E2%99%82%EF%B8%8F.ipynb?short_path=71ebc80#L3899

erro:
---------------------------------------------------------------------------
UnicodeDecodeError                        Traceback (most recent call last)
~\AppData\Local\Temp\ipykernel_14976\1639511343.py in <module>
----> 1 covid_infections_and_deaths = get_covid_infections_and_deaths()

~\AppData\Local\Temp\ipykernel_14976\2473027153.py in get_covid_infections_and_deaths(folder, filename)
      1 def get_covid_infections_and_deaths(folder='data', filename='ALL_HIST_PAINEL_COVID.csv'):
      2     _, filepath = build_path(folder, 'raw', filename)
----> 3     return pd.read_csv(filepath, sep=';', parse_dates = ['data'],\
      4                        dtype={'codmun': 'Int64', \
      5                               'codRegiaoSaude': 'Int64', \

~\anaconda3\lib\site-packages\pandas\io\parsers\readers.py in read_csv(filepath_or_buffer, sep, delimiter, header, names, index_col, usecols, dtype, engine, converters, true_values, false_values, skipinitialspace, skiprows, skipfooter, nrows, na_values, keep_default_na, na_filter, verbose, skip_blank_lines, parse_dates, infer_datetime_format, keep_date_col, date_parser, date_format, dayfirst, cache_dates, iterator, chunksize, compression, thousands, decimal, lineterminator, quotechar, quoting, doublequote, escapechar, comment, encoding, encoding_errors, dialect, on_bad_lines, delim_whitespace, low_memory, memory_map, float_precision, storage_options, dtype_backend)
    910     kwds.update(kwds_defaults)
    911 
--> 912     return _read(filepath_or_buffer, kwds)
    913 
    914 

~\anaconda3\lib\site-packages\pandas\io\parsers\readers.py in _read(filepath_or_buffer, kwds)
    581 
    582     with parser:
--> 583         return parser.read(nrows)
    584 
    585 

~\anaconda3\lib\site-packages\pandas\io\parsers\readers.py in read(self, nrows)
   1702                     columns,
   1703                     col_dict,
-> 1704                 ) = self._engine.read(  # type: ignore[attr-defined]
   1705                     nrows
   1706                 )

~\anaconda3\lib\site-packages\pandas\io\parsers\c_parser_wrapper.py in read(self, nrows)
    232         try:
    233             if self.low_memory:
--> 234                 chunks = self._reader.read_low_memory(nrows)
    235                 # destructive to chunks
    236                 data = _concatenate_chunks(chunks)

~\anaconda3\lib\site-packages\pandas\_libs\parsers.pyx in pandas._libs.parsers.TextReader.read_low_memory()

~\anaconda3\lib\site-packages\pandas\_libs\parsers.pyx in pandas._libs.parsers.TextReader._read_rows()

~\anaconda3\lib\site-packages\pandas\_libs\parsers.pyx in pandas._libs.parsers.TextReader._tokenize_rows()

~\anaconda3\lib\site-packages\pandas\_libs\parsers.pyx in pandas._libs.parsers.TextReader._check_tokenize_status()

~\anaconda3\lib\site-packages\pandas\_libs\parsers.pyx in pandas._libs.parsers.raise_parser_error()

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe3 in position 87428: invalid continuation byte

---------------------------------------------------------------------------

Me parece que no final da definição da função, vamos precisar adicionar o parâmetro encoding

Local de def da função:  https://github.com/heliomacedofilho/aspectos-de-programacao-para-ciencia-de-dados/blob/main/06%20-%20Ana%CC%81lise%20de%20Dados%20%F0%9F%95%B5%F0%9F%8F%BD%20%F0%9F%8E%B2%20em%20Alto%20Desempenho%20%F0%9F%9A%80%20%F0%9F%A7%9E%E2%80%8D%E2%99%82%EF%B8%8F.ipynb?short_path=71ebc80#L3282

Talvez algo do tipo:
def get_covid_infections_and_deaths(folder='data', filename='ALL_HIST_PAINEL_COVID.csv'):
    _, filepath = build_path(folder, 'raw', filename)
    return pd.read_csv(filepath, sep=';', parse_dates=['data'],
                       dtype={'codmun': 'Int64',
                              'codRegiaoSaude': 'Int64',
                              'populacaoTCU2019': 'Int64',
                              'casosAcumulado': 'Int64',
                              'Recuperadosnovos': 'Int64',
                              'emAcompanhamentoNovos': 'Int64',
                              'interior/metropolitana': 'Int64'},
                       encoding='XXX')

**Comment by heliomacedofilho** [comment]
Curioso. O padrão do pandas é usar encoding='utf-8'. Fiz o seguinte ajuste: adicionei o parâmetro utf-8 tanto na escrita do arquivo na aula 03, quanto na leitura do arquivo nesta aula.
