### ISSUE TITLE
Senti falta de uma explicação sobre índice

### ISSUE THREAD

**Issue by thaissalzer** [heliomacedofilho/aspectos-de-programacao-para-ciencia-de-dados#4]
Na aula 1 e 2 temos exemplos de como acessar elementos por índice, mas senti falta de uma explicação rápida sobre isso. Algo como:

Os índices em Python começam em 0, ou seja, o primeiro elemento de uma sequência tem o índice 0, o segundo elemento tem o índice 1, e assim por diante.

Avaliar se vcs acham necessário, ou se o pré-requisito do curso já englobaria isso

**Comment by heliomacedofilho** [comment]
bem percebido. na bibliografia, ele cita brevemente na parte de tuplas (aula 02). acredito que o ideal é citarmos na primeira vez que fazemos o uso de índice, na primeira aula, seção "Objetos Mutáveis e Imutáveis"
